module.exports = {
  fi: {
    '0': {
      a: 'Yleistä',
      b: 'Web-sovelluksen toimintaperiaatteita',
    },
    '1': {
      a: 'Reactin alkeet',
      b: 'Javascriptiä',
      c: 'Komponentin tila ja tapahtumankäsittely',
      d: 'Monimutkaisempi tila, Reactin debuggaus',
    },
    '2': {
      a: 'Kokoelmien renderöinti ja moduulit',
      b: 'Lomakkeiden käsittely',
      c: 'Palvelimella olevan datan hakeminen',
      d: 'Palvelimella olevan datan muokkaaminen',
      e: 'Tyylien lisääminen React-sovellukseen',
    },
    '3': {
      a: 'Node.js ja Express',
      b: 'Sovellus internetiin',
      c: 'Tietojen tallettaminen MongoDB-tietokantaan',
      d: 'Validointi ja ESLint',
    },
    '4': {
      a: 'Sovelluksen rakenne ja testauksen alkeet',
      b: 'Backendin testaaminen',
      c: 'Käyttäjien hallinta',
      d: 'Token-perustainen kirjautuminen',
    },
    '5': {
      a: 'Kirjautuminen frontendissä',
      b: 'props.children ja proptypet',
      c: 'React-sovellusten testaaminen',
      d: 'End to end -testaus',
    },
    '6': {
      a: 'Flux-arkkitehtuuri ja Redux',
      b: 'Monta reduseria',
      c: 'Redux-sovelluksen kommunikointi palvelimen kanssa',
      d: 'connect',
    },
    '7': {
      a: 'React-router',
      b: 'custom-hookit',
      c: 'Lisää tyyleistä',
      d: 'Webpack',
      e: 'Luokkakomponentit, Sekalaista',
      f: 'Tehtäviä: blogilistan laajennus',
    },
    '8': {
      a: 'GraphQL-palvelin',
      b: 'React ja GraphQL',
      c: 'Tietokanta ja käyttäjien hallinta',
      d: 'Kirjautuminen ja välimuistin päivitys',
      e: 'Fragmentit ja subskriptiot',
    },
    '9': {},
    '10': {},
    '11': {},
  },
  en: {
    '0': {
      a: 'General info',
      b: 'Fundamentals of Web apps',
    },
    '1': {
      a: 'Introduction to React',
      b: 'JavaScript',
      c: 'Component state, event handlers',
      d: 'A more complex state, debugging React apps',
    },
    '2': {
      a: 'Rendering a collection, modules',
      b: 'Forms',
      c: 'Getting data from server',
      d: 'Altering data in server',
      e: 'Adding styles to React app',
    },
    '3': {
      a: 'Node.js and Express',
      b: 'Deploying app to internet',
      c: 'Saving data to MongoDB',
      d: 'Validation and ESLint',
    },
    '4': {
      a: 'Structure of backend application, introduction to testing',
      b: 'Testing the backend',
      c: 'User administration',
      d: 'Token authentication',
    },
    '5': {
      a: 'Login in frontend',
      b: 'props.children and proptypes',
      c: 'Testing React apps',
      d: 'End to end -testing',
    },
    '6': {
      a: 'Flux-architecture and Redux',
      b: 'Many reducers',
      c: 'Communicating with server in a redux application',
      d: 'connect',
    },
    '7': {
      a: 'React-router',
      b: 'Custom hooks',
      c: 'More about styles',
      d: 'Webpack',
      e: 'Class components, Miscellaneous',
      f: 'Exercises: extending the bloglist',
    },
    '8': {
      a: 'GraphQL-server',
      b: 'React and GraphQL',
      c: 'Database and user administration',
      d: 'Login and updating the cache',
      e: 'Fragments and subscriptions',
    },
    '9': {
      a: 'Background and introduction',
      b: 'First steps with TypeScript',
      c: 'Typing the express app',
      d: 'React with types',
    },
    '10': {
      a: 'Introduction to React Native',
      b: 'React Native basics',
      c: 'Communicating with server',
      d: 'Testing and extending our application',
    },
    '11': {
      a: 'Introduction to CI/CD',
      b: 'Getting started with GitHub Actions',
      c: 'Deployment',
      d: 'Keeping green',
      e: 'Expanding Further',
    },
  },
  zh: {
    '0': {
      a: '基础知识',
      b: 'Web 应用的基础设施',
    },
    '1': {
      a: 'React 简介',
      b: 'JavaScript',
      c: '组件状态，事件处理',
      d: '深入React 应用调试',
    },
    '2': {
      a: '从渲染集合到模块学习',
      b: '表单',
      c: '从服务器获取数据',
      d: '在服务端将数据Alert出来',
      e: '给React应用加点样式',
    },
    '3': {
      a: 'Node.js 与 Express',
      b: '把应用部署到网上',
      c: '将数据存入MongoDB',
      d: 'ESLint与代码检查',
    },
    '4': {
      a: '从后端结构到测试入门',
      b: '测试后端应用',
      c: '用户管理',
      d: '密钥认证',
    },
    '5': {
      a: '完成前台的登录功能',
      b: 'props.children 与 proptypes',
      c: '测试React 应用',
      d: '端到端测试',
    },
    '6': {
      a: 'Flux架构与Redux',
      b: '再来点 reducers',
      c: '在Redux应用中与后端通信',
      d: 'connect方法',
    },
    '7': {
      a: 'React-router',
      b: '自定义 hooks',
      c: '样式进阶',
      d: 'Webpack',
      e: '各种各样的Class components',
      f: '练习：扩展你的博客列表',
    },
    '8': {
      a: 'GraphQL服务器',
      b: 'React 与 GraphQL',
      c: '数据库与用户管理',
      d: '登录与更新缓存',
      e: 'Fragments 与 subscriptions',
    },
    '9': {
      a: '背景与介绍',
      b: 'TypeScript的一小步',
      c: 'TypeScript版的express应用',
      d: '利用TypeScript编写React应用',
    },
    '10': {
      a: 'React Native 介绍',
      b: 'React Native 入门',
      c: '与服务端通信',
      d: '测试与扩展我们的应用',
    },
    '11': {
      a: 'CI/CD 简介',
      b: '开始认识 GitHub Actions 吧',
      c: '部署',
      d: '保持健康状态',
      e: '再扩展一下',
    },
  },
  es: {
    '0': {
      a: 'Información general',
      b: 'Fundamentos de las aplicaciones web',
    },
    '1': {
      a: 'Introducción a React',
      b: 'JavaScript',
      c: 'Estado del componente, controladores de eventos',
      d: 'Un estado más complejo, depurando aplicaciones React',
    },
    '2': {
      a: 'Renderizando una colección, módulos',
      b: 'Formularios',
      c: 'Obteniendo datos del servidor',
      d: 'Alterando datos en el servidor',
      e: 'Agregar estilos a la aplicación React',
    },
    '3': {
      a: 'Node.js y Express',
      b: 'Implementación de la aplicación en Internet',
      c: 'Guardando datos en MongoDB',
      d: 'Validación y ESLint',
    },
    '4': {
      a: 'Estructura de la aplicación backend, introducción a las pruebas',
      b: 'Porbando el backend',
      c: 'Administración de usuarios',
      d: 'Autenticación de token',
    },
    '5': {
      a: 'Iniciar sesión en la interfaz',
      b: 'props.children y proptypes',
      c: 'Probando aplicaciones React',
      d: 'Pruebas de extremo a extremo',
    },
    '6': {
      a: 'Flux-architecture y Redux',
      b: 'Muchos reducers',
      c: 'Comunicarse con el servidor en una aplicación redux',
      d: 'conectar',
    },
    '7': {
      a: 'React-router',
      b: 'Hooks personalizados',
      c: 'Más sobre estilos',
      d: 'Webpack',
      e: 'Componentes de clases, varios',
      f: 'Ejercicios: ampliar la lista de blogs',
    },
    '8': {
      a: 'Servidor GraphQL',
      b: 'React y GraphQL',
      c: 'Administración de bases de datos y usuarios',
      d: 'Iniciar sesión y actualizar la caché',
      e: 'Fragmentos y suscripciones',
    },
    '9': {
      a: 'Antecedentes e introducción',
      b: 'Primeros pasos con TypeScript',
      c: 'Escribiendo la aplicación express',
      d: 'React con tipos',
    },
    '10': {
      a: 'Introducción a React Native',
      b: 'Conceptos básicos de React Native',
      c: 'Comunicandose con el servidor',
      d: 'Probar y ampliar nuestra aplicación',
    },
    '11': {
      a: 'Introducción a CI/CD',
      b: 'Introducción a las acciones de Github',
      c: 'Despliegue',
      d: 'Manteniéndose verde',
      e: 'Expandiéndose aún más'
    },
  },
};
