module.exports = [
  'fullstack',
  'full stack open 2019',
  'course',
  'helsingin yliopisto',
  'tietojenkäsittelytieteen osasto',
  'mooc',
  'mooc.fi',
  'full stack',
  'full stack open',
  'web-sovelluskehitys',
  'web',
  'houston',
  'houston inc',
  'websovelluskehitys',
  'web-sovellus',
  'React',
  'Redux',
  'Node.js',
  'Node',
  'MongoDB',
  'GraphQL',
  'REST',
  'REST api',
  'single page -sovellus',
  'ohjelmointi'
];
